name: santitools CI

on:
  push:
    branches: [ main ]
    paths:
      - src/**/*.*
      - .github/workflows/*.*

  pull_request:
    branches: [ main ]
    paths: 
      - src/**/*.*
      - .github/workflows/*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
        with:
          version: 3.10.9

      - name: Install Pytest
        run: |
          pip install pytest==7.2.1
      - name: Install the project in editable mode
        run: pip install -e .
      - name: Run Pytest
        run: |
          pytest tests
  publish: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: pip install build twine virtualenv
      - name: Build files
        run: python3 -m build
      - name: Publish with twine
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_AUTH_TOKEN }}
