name: Continuous Deployment (CD)

on:
  workflow_call:
    secrets:
      PYPI_AUTH_TOKEN:
        required: true
      GPR_AUTH_TOKEN:
        required: true
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          version: 3.10.9
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Install twine
        run: pip install twine
      - name: Decompress artifact
        run: tar -xf dist.tar 
      - name: Publish with twine
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_AUTH_TOKEN }}
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11.2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Install twine
        run: pip install twine
      - name: Decompress artifact
        run: tar -xf dist.tar 
      - name: Publish with twine
        run: python3 -m twine upload dist/* --repository-url https://pip.pkg.github.com
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GPR_AUTH_TOKEN }}

