name: Continuous Integration (CI)

on:
  push:
    branches: 
      - main
    paths:
      - src/**/*.*
      - .github/workflows/*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11.2

      - name: Install Pytest
        run: |
          pip install pytest==7.2.1
      - name: Install the project in editable mode
        run: pip install -e .
      - name: Run Pytest
        run: |
          pytest tests
  build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: pip install build virtualenv
      - name: Build files
        run: python3 -m build
      - name: Package distributions
        run: tar -cf dist.tar dist 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.tar
  release:
    needs: build
    uses: ./.github/workflows/release.yml
    secrets:
      PYPI_AUTH_TOKEN: ${{ secrets.PYPI_AUTH_TOKEN }}
      GPR_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
      GH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}